### ISSUE TITLE
Access BS1-UE1 data in Dynamic Doppler (DD1) Scenario using v3

### ISSUE THREAD

**Issue by abdullah-alahmadi** [DeepMIMO/DeepMIMO-python#4]
I have a question about the total number of UEs in Dynamic Doppler (DD1) Scenario, the [website](https://www.deepmimo.net/scenarios/dynamic-doppler-dd1/ ) does not mention that. but from figure 2 it seems that there are 3 UEs. How can I access a specific link data between BS and UE (say BS1 and UE1).

Thank you

**Comment by jmoraispk** [comment]
Hi @abdullah-alahmadi 
Thanks for bringing this to our attention. We probably should make an example with dynamic scenarios. 

In any case, you can find it the [DeepMIMOv3 docs](https://www.deepmimo.net/versions/deepmimo-v3-python/). After generating the dataset, you'll have a deepMIMO_scenario which is a list of snapshots (or scenes) across time. deepMIMO_scenario[0] will list the datastets of each basestation for the first time sample. deepMIMO_scenario[0][0] is a dictionary for the first basestation. deepMIMO_scenario[0][0]['user']['location'] would give you the locations of those 3 users, which should match across basestations. deepMIMO_scenario[0][0]['user']['channel'] would give you channel between each user and basestation 0. The only difference between DD1 and the other scenarios in terms of how to access the data is the existence of "scenes" since it's a dynamic scenario, so it needs double indexing. 

For more info, see the [output parameters](https://www.deepmimo.net/versions/deepmimo-v3-python/#elementor-toc__heading-anchor-5) section in the docs

**Comment by abdullah-alahmadi** [comment]
Thanks @jmoraispk. But when running dataset[0][0]['user']['location'] it gives an array [5,3]. Does this mean we have 5 users?

**Comment by jmoraispk** [comment]
@abdullah-alahmadi, exactly. 3 would be the dimension of the each location, XYZ. The website mentions that the number of users can vary across scenes, since users are passing cars randomly generated.

**Comment by Shunqiang-Feng** [comment]
Hello @jmoraispk , I would like to ask about the dyn_doppler_DD1_28 scenario in DeepMIMO MATLAB v3 (the same issue also appears in the Python version). It seems that this scenario is no longer available in v4.

I attempted to generate data using v3, but encountered a problem with the params.active_user_last parameter. The current official website no longer provides documentation for this parameter in this scenario . When running the code, I receive the following error:

"There are total 1 user rows in the scenario, please select the active user first and last in [1, 1]"

However, when I set params.active_user_last = 1, the generated output only includes BS-to-BS channels and does not contain any BS-to-UE channels. 2 months ago, I was able to generate BS-to-UE channels for this scenario, but I can no longer do so. I’m unsure whether I made a mistake or if there have been updates to the dataset generation process.

<img width="701" height="334" alt="Image" src="https://github.com/user-attachments/assets/a0350a48-2c3f-4798-b6c3-703138b1274b" />

Could you please advise me on how to resolve this issue?

Best regards,
Shunqiang Feng

**Comment by jmoraispk** [comment]
Hi @Shunqiang-Feng

There is a Legacy menu with the previous versions of DeepMIMO. There you have an exact copy of the previous documentations and the scenario files. Are you trying the right software with the right scenario version?

**Comment by Shunqiang-Feng** [comment]
@jmoraispk Hi, I visited **https://deepmimo.net/versions/legacy#v3**,  and I used the python v3, and downloaded data from scenario v3, the figure above is not matlab v3, it was a previous version (maybe). But the matlab v3 is also wrong, which returned a struct with all zero user CELL. For python v3, the problem is the same, you can see the log below, no user data inclued:

<img width="1459" height="839" alt="Image" src="https://github.com/user-attachments/assets/a8c00bd7-4049-4edd-b3c8-233ab7ecfae4" />

**Comment by jmoraispk** [comment]
Is it possible that there are no users with data on row 1? I am not entirely sure how dynamic scenarios worked in v3.

Btw, DeepMIMO v4 has the O1 scenario at multiple frequencies with the ability to add Doppler (in 2 different ways). In that sense, it is more flexible than the DD1 in v3. You can see an example of [Doppler in v4 here](https://deepmimo.net/docs/manual_full.html#doppler)

**Comment by Shunqiang-Feng** [comment]
Good. if v4 can support, that would be even better! Let me have a try.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Shunqiang-Feng** [comment]
@jmoraispk Hi, thanks for the tip.  O1_28 can set Doppler in a more flexible way. However, I cannot use 
```
# Different Doppler shift for different users and paths
dopplers3 = np.random.randint(20, 51, size=(dataset.n_ue, dataset.max_paths))
dataset.set_doppler(dopplers3)
dataset.compute_channels(dm.ChannelParameters(doppler=True))
```

The error shows:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[10], line 3
      1 # Create channel parameters with all options
      2 ch_params = dm.ChannelParameters(doppler = True)
----> 3 dopplers = np.random.randint(90, 180, size=(dataset.n_ue, dataset.max_paths)) # 1~2 m/s
      6 # Antenna parameters
      7 
      8 # Base station antenna parameters
      9 ch_params.bs_antenna.rotation = np.array([0, 0, 0])  # [az, el, pol] in degrees

File numpy/random/mtrand.pyx:796, in numpy.random.mtrand.RandomState.randint()

File numpy/random/_bounded_integers.pyx:1343, in numpy.random._bounded_integers._rand_int64()

TypeError: 'list' object cannot be interpreted as an integer
```

Then I print
```
print(type(dataset.n_ue), dataset.n_ue)
print(type(dataset.max_paths), dataset.max_paths)
```

I get:
```
<class 'list'> [497931, 199281, 487711, 497931, 199281, 487711, 497931, 199281, 487711, 497931, 199281, 487711, 497931, 199281, 487711, 497931, 199281, 487711, 497931, 199281, 487711, 497931, 199281, 487711, 497931, 199281, 487711, 497931, 199281, 487711, 497931, 199281, 487711, 497931, 199281, 487711, 497931, 199281, 487711, 497931, 199281, 487711, 497931, 199281, 487711, 497931, 199281, 487711, 497931, 199281, 487711, 497931, 199281, 487711]
<class 'list'> [DeepMIMOArray(16), DeepMIMOArray(12), DeepMIMOArray(10), DeepMIMOArray(17), DeepMIMOArray(8), DeepMIMOArray(8), DeepMIMOArray(12), DeepMIMOArray(7), DeepMIMOArray(9), DeepMIMOArray(17), DeepMIMOArray(10), DeepMIMOArray(7), DeepMIMOArray(11), DeepMIMOArray(12), DeepMIMOArray(7), DeepMIMOArray(15), DeepMIMOArray(17), DeepMIMOArray(15), DeepMIMOArray(13), DeepMIMOArray(14), DeepMIMOArray(18), DeepMIMOArray(14), DeepMIMOArray(17), DeepMIMOArray(9), DeepMIMOArray(15), DeepMIMOArray(16), DeepMIMOArray(14), DeepMIMOArray(14), DeepMIMOArray(17), DeepMIMOArray(10), DeepMIMOArray(13), DeepMIMOArray(11), DeepMIMOArray(17), DeepMIMOArray(18), DeepMIMOArray(10), DeepMIMOArray(8), DeepMIMOArray(17), DeepMIMOArray(10), DeepMIMOArray(8), DeepMIMOArray(17), DeepMIMOArray(7), DeepMIMOArray(9), DeepMIMOArray(17), DeepMIMOArray(13), DeepMIMOArray(10), DeepMIMOArray(17), DeepMIMOArray(8), DeepMIMOArray(7), DeepMIMOArray(17), DeepMIMOArray(8), DeepMIMOArray(7), DeepMIMOArray(18), DeepMIMOArray(10), DeepMIMOArray(6)]
```

I assume that o1_28 is designed for multiple scenes. Do you know how to set doppler for different users, different paths, different scenes?

Thanks for your attention.

**Comment by Shunqiang-Feng** [comment]
@jmoraispk In addition, v4 seems not to support random rotation angle, I tried to set `ch_params.bs_antenna.rotation = np.array([[0, 360], [0, 30], [0,0]])` but get error `AssertionError: The BS antenna rotation must be a 3D vector`. Is there any way to set random rotation angle? Thanks for your time.

**Comment by jmoraispk** [comment]
@Shunqiang-Feng - The problem with O1 is not "dynamic scenes". It's multiple BSs. When you load with just dm.load(), it loads all BSs and user grids. Check the "load" and "scenario_info" sections. 

That code works if you select only a single BS and single RX grid:
```
multi_dataset = np.load('o1_28')
single_dataset = np.load('o1_28', tx_sets=[10], rx_sets=[1])
```

If you do `multi_dataset[0].n_ue` or `single_dataset.n_ue`, now you will see only a single number, and the doppler code will work.

**Comment by jmoraispk** [comment]
@Shunqiang-Feng , regarding the random rotations, you're right. I must have dropped this feature by mistake when refactoring that part. I'll add it back.

**Comment by Shunqiang-Feng** [comment]
@jmoraispk Great! Thanks! Your advice works. Ok, take your time, this feature is important, because researchers always need diverse csi as training data. Please reply to this message when you finish it! 💯

**Comment by jmoraispk** [comment]
Btw. I just pushed something that makes `single_dataset.max_paths` return an actual `int`.
So you shouldn't see that ugly list of DeepMIMO arrays again. (in next version or if you pull)

**Comment by jmoraispk** [comment]
@Shunqiang-Feng , turns out I didn't remove the feature. The random angles are just for the ue antennas. it works if you do `ch_params.ue_antenna.rotation = np.array([[0, 360], [0, 30], [0,0]])`. 

Since each "dataset" is single BS, I think it doesn't make much sense to have it for the BS too. 
What do you think? Does randomizing angles for the users already provide enough variability?

**Comment by Shunqiang-Feng** [comment]
Thank you for your reply. I have designed a custom dataset for my project, which involves an AoD prediction task. In my algorithm, since the AoD spectrum lacks diversity without BS rotation, I included BS rotation in my dataset. For my use case, BS rotation is much more important than UE rotation, as I place less emphasis on AoA.

In my opinion, if it's not too difficult to add BS rotation, I would suggest including it. This would not only make the API for both UE and BS more consistent, but also provide users with more flexibility — allowing them to decide whether or not they need this feature.

**Comment by jmoraispk** [comment]
Thanks for the feedback @Shunqiang-Feng . I agree. 

I've implemented it for the BS too.
Additionally, I've now set the antenna rotations with the random angle realization. So, each iteration of compute_channels you can check `dataset.ch_params.bs_antenna` for the specific realizations. 

Note that you if you want random rotations each time, you need to call `dataset.compute_channels(ch_params)` each time. 

If you instead do:
```
dataset.set_channel_params(ch_params)
for i in ...:
    dataset.compute_channels()
```
You'll always get the same realization since the channel parameters will be cached. 

This will still work to generate random channels in each iteration, since the cache gets reset when new parameters are assigned:
```
ch_params = dm.ChannelParameters()
ch_params.bs_antenna.rotation = np.array([[0, 360], [0, 30], [0,0]])
for i in ...:
    dataset.set_channel_params(ch_params)
    dataset.compute_channels()
```

**Comment by Shunqiang-Feng** [comment]
@jmoraispk Great! Thanks for your update and contribution. It helps a lot. Just to confirm, now I can get the latest python version via `pip install --pre deepmimo` right?

**Comment by jmoraispk** [comment]
@Shunqiang-Feng For the latest changes, it is better if you clone the [repository](https://github.com/DeepMIMO/DeepMIMO) and install from inside the cloned folder with `pip install .` (if you want to eventually change the code and have it reflect directly, do `pip install -e .`)

There are a few verifications we need to do, so a new partial release might come only a bit later.

**Comment by Shunqiang-Feng** [comment]
@jmoraispk Ok, thanks for the patient explanation. I will clone the respository and run code tomorrow or later. Take your time. 👍

**Comment by Shunqiang-Feng** [comment]
Hi, I would like to confirm whether the following code:
```
dopplers3 = np.random.randint(20, 51, size=(dataset.n_ue, dataset.max_paths)) 
dataset.set_doppler(dopplers3)
dataset.compute_channels(dm.ChannelParameters(doppler=True))
```

applies the Doppler effect only to the Tx or Rx motion, rather than introducing Doppler effects from other moving objects in the environment. Is that correct?

**Comment by jmoraispk** [comment]
This applies the doppler shift directly to the paths between tx-rx. Other objects are not considered - as you see, we are not specifying them. If you want, you can set speeds per object and per rx/tx, and then the paths will be affected also by the objects, and the speeds assigned will be projects onto the paths that interact with those moving entities.
