### ISSUE TITLE
How to apply DeepMIMO to wideband issue?

### ISSUE THREAD

**Issue by Trans-cending** [DeepMIMO/DeepMIMO-python#5]
Hello! Thanks for the wonderful emulated public dataset. But I have some questions when using it to generate dataset for wideband communication research. I can activate OFDM channel, but the antenna spacing is fixed and the central frequency cannot be set, which means I cannot use it to simulate wideband effects, such as beam squint. How can I do to modify it to apply to the wideband scenario? Thanks.

**Comment by jmoraispk** [comment]
Hi @Trans-cending 

As far as I know, the antenna spacing is not fixed. It is a configurable parameter. Can you show me how you tried to change it?

**Comment by Trans-cending** [comment]
Hi @jmoraispk. Thanks for your reply. What I mean is that the frequency-domain channel model is related to central frequency (fc) and bandwidth (so the subcarrier is fk instead of fc) instead of just antenna spacing (0.5c/fc generally). I wonder if the effect of bandwidth and center frequency on the response vector in the channel model is ignored because the bandwidth is assumed to be small relative to the center frequency. Thanks.

**Comment by jmoraispk** [comment]
That is true. That assumption is made because the material response we get in the RayTracing also depends with frequency, and far off the center frequency, the materials would respond differently. 

Nevertheless, I see how it could be helpful for wideband studies, even if the channels aren't the most accurate. Then, you may change the channel model equation to fit your needs - that is largely a reason why DeepMIMO is open source. Is that what you were trying to do from the beginning?

**Comment by Trans-cending** [comment]
Thanks for reply. But I am still a little bit confused. I reviewed the configuration code and "DeepMIMO channel model". The central frequency is predefined based on the downloaded dataset, for example, 'O1_28' means the central frequency is 28 GHz. So I would like to confirm that whether d is related to only central frequency fc instead of frequencies of K subcarriers fk or not.

**Comment by Trans-cending** [comment]
Moreover, in some cases, there can be some warnings like "ToA of some paths of xxx channels with an average total power of 100.00% exceed the useful OFDM symbol duration and are clipped." How can I solve this? Thanks

**Comment by jmoraispk** [comment]
The distance between elements is based on the central frequency. It doesn't change across the band. Does this answer your question?

Regarding the warning, it is because the symbol duration is too small, compared with the time of arrival of the paths. If the path is so long that it arrives in the next OFDM symbol, we consider it will be caught on cyclic prefix and we don't include it in the channel. 

You can see this in line 19-20 of utils.py:
```
Ts = 1 / (params[c.PARAMSET_OFDM][c.PARAMSET_OFDM_BW]*c.PARAMSET_OFDM_BW_MULT)
self.FFT_duration = params[c.PARAMSET_OFDM][c.PARAMSET_OFDM_SC_NUM] * Ts
```

Ts is the time of a single sample. A OFDM symbol will have FFT_SIZE number of samples, so the symbol duration will be Ts * FFT_SIZE = FFT_DURATION, and any path beyond this number will be cut off. You are having this warning, you may have set the bandwidth too large, or included too few subcarriers. 

Let me know if any further clarification is needed. And thank you for your question. It shows that perhaps we should have made this path cuttoff optional. If you would like to turn it off, you can comment out the respective line in the code that performs the verification. In Python, line 94 in `raytracing_v3.py`

**Comment by Trans-cending** [comment]
Thanks for guidance. Thanks for your kindness.

**Comment by Trans-cending** [comment]
![image](https://github.com/user-attachments/assets/71fd3eef-8f3f-45dc-bba9-ff1de4b3ad69)
![image](https://github.com/user-attachments/assets/3822d018-61dc-418d-a53b-1bceb7e7e953)

Hello, in O1_28 scenario, it seems that the reflector overlaps with the blockage. So what is the exact location of the block? Thanks.

**Comment by jmoraispk** [comment]
Please post this in another issue. What incompatibility do you see?

**Comment by jmoraispk** [comment]
Comments about #6 moved there. Closing this issue.
